# Generated by Django 4.2.1 on 2024-02-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SentiAnalyser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=100)),
                ('content_description', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
