# Generated by Django 4.2.1 on 2024-02-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SentiAnalyser', '0002_analyzerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerdata',
            name='u_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
