# Generated by Django 4.2.1 on 2024-02-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SentiAnalyser', '0003_analyzerdata_u_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzerdata',
            name='u_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
